apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-mmi-client-external'
  labels:
    katenary.io/component: mmi-client-external
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: 817e1a57696cf49186bcb8a53d0979b0437f075d
    katenary.io/version: 2.0.0-beta2
spec:
  selector:
    katenary.io/component: mmi-client
    katenary.io/release: '{{ .Release.Name }}'
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
