apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-nginx'
  labels:
    katenary.io/component: nginx
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: 817e1a57696cf49186bcb8a53d0979b0437f075d
    katenary.io/version: 2.0.0-beta2
spec:
  replicas: 1
  selector:
    matchLabels:
      katenary.io/component: nginx
      katenary.io/release: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        katenary.io/component: nginx
        katenary.io/release: '{{ .Release.Name }}'
    spec:
      initContainers:
        - name: check-mmi-client
          image: busybox
          command:
            - sh
            - -c
            - |-
              OK=0
              echo "Checking mmi-client port"
              while [ $OK != 1 ]; do
                  echo -n "."
                  nc -z {{ .Release.Name }}-mmi-client 8000 2>&1 >/dev/null && OK=1 || sleep 1
              done
              echo
              echo "Done"
        - name: check-biap-client-node-js
          image: busybox
          command:
            - sh
            - -c
            - |-
              OK=0
              echo "Checking biap-client-node-js port"
              while [ $OK != 1 ]; do
                  echo -n "."
                  nc -z {{ .Release.Name }}-biap-client-node-js 3000 2>&1 >/dev/null && OK=1 || sleep 1
              done
              echo
              echo "Done"
      containers:
        - name: nginx
          image: '{{ .Values.nginx.repository.image }}{{ if ne .Values.nginx.repository.tag "" }}:{{ .Values.nginx.repository.tag }}{{ end }}'
          ports:
            - name: nginx
              containerPort: 80
            - name: nginx-443
              containerPort: 443
          env:
            - name: REACT_APP_FIREBASE_AUTH_DOMAIN
              value: '{{ tpl .Values.nginx.environment.REACT_APP_FIREBASE_AUTH_DOMAIN . }}'
            - name: REACT_APP_GOOGLE_API_KEY
              value: '{{ tpl .Values.nginx.environment.REACT_APP_GOOGLE_API_KEY . }}'
            - name: REACT_APP_BASE_URL
              value: '{{ tpl .Values.nginx.environment.REACT_APP_BASE_URL . }}'
            - name: REACT_APP_MMI_BASE_URL
              value: '{{ tpl .Values.nginx.environment.REACT_APP_MMI_BASE_URL . }}'
            - name: REACT_APP_FIREBASE_API_KEY
              value: '{{ tpl .Values.nginx.environment.REACT_APP_FIREBASE_API_KEY . }}'

