#biap-client-node-js:
#  repository:
#    image: navdeep710/client-js-node
#    tag: ""
node_js_ondc_client:
  environment:
    JUSPAY_SECRET_KEY_PATH: "./config/dev/juspay.pem"
    JUSPAY_BASE_URL: "https://sandbox.juspay.in"
    JUSPAY_MERCHANT_ID: "ONDC"
    JUSPAY_API_KEY: "C20BA978F2C4B4D88CD6E1B159F2E7"
    FIREBASE_ADMIN_SERVICE_ACCOUNT: "./config/dev/firebase-service-account.json"
    ONDC_BASE_API_URL: "https://ref-app-buyer-staging-v2.ondc.org"
    JUSPAY_WEBHOOK_USERNAME: "ONDC"
    JUSPAY_WEBHOOK_PASSWORD: {{ .Values.JUSPAY_WEBHOOK_PASSWORD }}
    DOMAIN: "nic2004:52110"
    CITY: "std:080"
    COUNTRY: "IND"
    PROTOCOL_BASE_URL: "http://py-ondc-protocol:5555"

    BAP_ID: "ref-app-buyer-staging-v2.ondc.org"
    BAP_PUBLIC_KEY: "lPetySkn0oCUkj02pq3Hk7iNtM8/+Hf+V7jJwOcKHSk="
    BAP_UNIQUE_KEY_ID: "3b7ff621-0f32-46b6-8b51-df1f36602d6b"
    BAP_URL: "https://ref-app-buyer-staging-v2.ondc.org/protocol/v1"
    PORT: "3000"
    NODE_DEV: "dev"
    REGISTRY_BASE_URL: "https://staging.registry.ondc.org"
    ENV_TYPE: "STAGING"
    BAP_FINDER_FEE_TYPE: "percent"
    BAP_FINDER_FEE_AMOUNT: "3.0"
    SSE_TIMEOUT: "5000"
    MMI_CLIENT_SECRET: {{ .Values.MMI_CLIENT_SECRET }}
    MMI_CLIENT_ID: "33OkryzDZsK1N7inkldC0FhmxZmlSbqPIWsk2IZZWyXwbdoHrk_nXMsbMALA6dCBBinDcrUF-a6GCPTVxyotag=="
    AWS_ACCESS_KEY_ID: {{ .Values.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: {{ .Values.AWS_SECRET_ACCESS_KEY }}
    S3_VERSION: "v4"
    S3_REGION: "ap-south-1"
    S3_BUCKET: "reference-buyer-app-assets/public-assets"
    RAZORPAY_KEY_ID: "rzp_test_gA9rut0yNp9bjA"
    RAZORPAY_KEY_SECRET: {{ .Values.RAZORPAY_KEY_SECRET }}
    RAZORPAY_WEBHOOK_SECRET: {{ .Values.RAZORPAY_WEBHOOK_SECRET }}
    BHASHINI_REDIS_PORT: "26379"
    BHASHINI_REDIS_HOST: "34.118.226.20"
    BHASHINI_USERID: "91d3b9632f6e44aba6f134b78290d77f"
    BHASHINI_ULCA_API_KEY: {{ .Values.BHASHINI_ULCA_API_KEY }}
    DLT_CUSTOMER_ID: {{ .Values.DLT_CUSTOMER_ID }}
    DLT_ENTITY_ID: "1001265305956922411-1"
    DLT_USERNAME: "OPEN_NETWO_M5qy4uvAnJWNhAmihZt8-1"
    DLT_PASSWORD: {{ .Values.DLT_PASSWORD }}
    DLT_SOURCE: "ONDCNW-1"
    DLT_MESSAGE_TYPE: "SERVICE_IMPLICIT-1"
    CORS_WHITELIST_URLS: "https://ref-app-buyer-staging-v2.ondc.org,ref-app-buyer-staging-v2.ondc.org,http://localhost:3000,https://localhost:3000"
    ELASTIC_SEARCH_URL: "http://es-cluster-es-http.ondc-prod-prod.svc.cluster.local:9200"
  repository:
    image: "public.ecr.aws/l6b3l7s4/ondc-reference-buyer-app"
    tag: "clientsvcv1.1"
#
#mmi-client:
#  environment:
#    ENV: prod
#    KNOWLARITY_AGENT_NUMBER: ""
#    KNOWLARITY_API_KEY: ""
#    KNOWLARITY_AUTHORIZATION_HEADER_KEY: ""
#    KNOWLARITY_NUMBER: ""
#    MMI_ADVANCE_API_KEY: ""
#    MMI_CLIENT_ID: ""
#    MMI_CLIENT_SECRET: ""
#  repository:
#    image: navdeep710/ondc-ancillary-services
#    tag: v3
#
#nginx:
#  environment:
#    REACT_APP_BASE_URL: ""
#    REACT_APP_FIREBASE_API_KEY: ""
#    REACT_APP_FIREBASE_AUTH_DOMAIN: ""
#    REACT_APP_GOOGLE_API_KEY: ""
#    REACT_APP_MMI_BASE_URL: ""
#  repository:
#    image: navdeep710/ondc-nginx
#    tag: ""
py_ondc_protocol:
  environment:
    BAP_ID: "ref-app-buyer-staging-v2.ondc.org"
    BAP_PUBLIC_KEY: "lPetySkn0oCUkj02pq3Hk7iNtM8/+Hf+V7jJwOcKHSk="
    BAP_UNIQUE_KEY_ID: "3b7ff621-0f32-46b6-8b51-df1f36602d6b"
    BAP_URL: "https://ref-app-buyer-staging-v2.ondc.org/protocol/v1"
    REGISTRY_BASE_URL: "https://staging.registry.ondc.org"
    CLIENT_WEBHOOK_ENDPOINT: "https://ref-app-buyer-staging-v2.ondc.org/clientApis/response"
    ENV: "dev"
    EXPECTED_RESPONSE_TIME: "PT1H"
    FLASK_SERVER: "True"
    QUEUE_ENABLE: "False"
    ELASTIC_SEARCH_QUEUE_ENABLE: "True"
    VERIFICATION_ENABLE: "False"

  repository:
    image: "public.ecr.aws/l6b3l7s4/ondc-reference-buyer-app"
    tag: "protocolsvcv1.4"

catalog_service:
  environment:
    ENV: "dev"
    ELASTIC_SEARCH_URL: "http://es-cluster-es-internal-http.ondc-prod-prod.svc.cluster.local:9200"
    LANGUAGE_LIST: ""
    CONSUMER_MAX_WORKERS: "5"
    BULK_CHUNK_SIZE: "100"

  repository:
    image: "public.ecr.aws/l6b3l7s4/ondc-reference-buyer-app"
    tag: "catalogsvcv1.4"

mongodb:
  enabled: true
  name: "buyer-app-mongodb"
  namespace: "ondc-prod-prod"
  version: "6.0.5"
  # Configuration for MongoDB operator
  fullnameOverride: community-operator
  replicaCount: 1
  password: "password"
  port: "27018"
  nodeport: "30018"
  image:
    repository: "mongo"
    tag: "6.0.5"
  storage:
    size: "100Gi"
  resources:
    requests:
      memory: "4Gi"
      cpu: "500m"
    limits:
      memory: "4Gi"
      cpu: "500m"

redis:
  enabled: true
  namespace: "ondc-prod-prod"
  # Configuration for Redis operator
  fullnameOverride: redis-operator
  replicas: 1
  sentinel:
    replicas: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"

rabbitmq:
  enabled: false
  # Configuration for RabbitMQ operator
  fullnameOverride: rabbitmq-cluster-operator
  namespace: "ondc-prod-prod"
  replicas: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "500m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  persistence:
    storage: "100Gi"
    storageClassName: "standard-rwo"

elasticsearch:
  enabled: true
  fullnameOverride: elastic-operator
  version: "8.8.0"
  masterNodesCount: 1
  dataNodesCount: 1
  masterNodes:
    storage:
      storage: "100Gi"
      storageClassName: "standard-rwo"
    resources:
      requests:
        memory: "5Gi"
        cpu: "0.5"
      limits:
        memory: "5Gi"
        cpu: "0.5"
    java_resources:
      requests:
        memory: "4G"
        cpu: "0.5"
      limits:
        memory: "4G"
        cpu: "0.5"
  dataNodes:
    storage:
      storage: "500Gi"
      storageClassName: "standard-rwo"
    resources:
      requests:
        memory: "3Gi"
        cpu: "0.5"
      limits:
        memory: "3Gi"
        cpu: "0.5"
    java_resources:
      requests:
        memory: "2G"
        cpu: "0.5"
      limits:
        memory: "2G"
        cpu: "0.5"
  ingestNodesCount: 1
  ingestNodes:
    storage:
      storage: "100Gi"
      storageClassName: "standard-rwo"
    resources:
      requests:
        memory: "3Gi"
        cpu: "0.5"
      limits:
        memory: "3Gi"
        cpu: "0.5"
    java_resources:
      requests:
        memory: "2G"
        cpu: "0.5"
      limits:
        memory: "2G"
        cpu: "0.5"
global:
  namespace: "ondc-prod-prod"
  storageClass: "standard-rwo"
