apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: '{{ .Values.global.namespace }}'
  name: '{{ .Release.Name }}-frontend-service'
  labels:
    app: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: '{{ (lookup "v1" "ConfigMap" .Values.global.namespace "frontend-service-version-config").data.image_tag }}'
          ports:
            - name: pyport
              containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  namespace: '{{ .Values.global.namespace }}'
  name: '{{ .Release.Name }}-frontend-service-external'
  labels:
    app: frontend-service
spec:
  selector:
    app: frontend-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
