apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redis-cluster
spec:
  sentinel:
    replicas: {{ .Values.redis.sentinel.replicas }}
  redis:
    replicas: {{ .Values.redis.replicas }}
    resources:
      requests:
        memory: {{ .Values.redis.resources.requests.memory }}
        cpu: {{ .Values.redis.resources.requests.cpu }}
      limits:
        memory: {{ .Values.redis.resources.limits.memory }}
        cpu: {{ .Values.redis.resources.limits.cpu}}