apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: {{ .Values.mongodb.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  members: {{ .Values.mongodb.replicaCount }}
  type: ReplicaSet
  version: {{ .Values.mongodb.version }}
  security:
    authentication:
      modes: [ "SCRAM" ]
  users:
    - name: my-mongodb-admin
      roles:
        - name: dbAdmin
          db: admin
        - name: readWrite
          db: sandbox_bap
      db: admin
      passwordSecretRef:
        name: my-mongodb-admin-password
      scramCredentialsSecretName: my-mongodb
  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: {{ .Values.mongodb.storage.size }}
      template:
        spec:
          containers:
            - name: mongodb
              image: {{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}
              ports:
                - containerPort: 27017
              volumeMounts:
                - name: data-volume
                  mountPath: /data/db
              resources:
                requests:
                  memory: {{ .Values.mongodb.resources.requests.memory }}
                  cpu: {{ .Values.mongodb.resources.requests.cpu }}
                limits:
                  memory: {{ .Values.mongodb.resources.limits.memory }}
                  cpu: {{ .Values.mongodb.resources.limits.cpu }}

---
apiVersion: v1
kind: Secret
metadata:
  name: my-mongodb-admin-password
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  password: "adminpassword"