apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-catalog-service-external'
  labels:
    katenary.io/component: catalog-service-external
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
spec:
  selector:
    katenary.io/component: catalog-service
    katenary.io/release: '{{ .Release.Name }}'
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555
  type: NodePort
