apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.global.namespace }}
  name: app-ingress
spec:
  rules:
    - host: elastic.ondcapp.dataorc.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: es-cluster-es-http
                port:
                  number: 9200

