apiVersion: v1
kind: ConfigMap
metadata:
  name: catalog-clean-cron-version-config
  namespace: ondc-prod-prod
data:
  image_tag: "public.ecr.aws/l6b3l7s4/ondc-reference-buyer-app:catalogcleancronv1.0"
